org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

mod_version=1.4.3
works_for_version=26.2
maven_group=com.twinsession
archives_base_name=twinsession

fabric_api_version=0.156.0+26.2
jacoco_version=0.8.14
lombok_version=9.5.0
luckperms_version=5.4
